FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY BE /app/BE
COPY ml /app/ml

ENV PYTHONPATH=/app
CMD ["uvicorn", "BE.main:app", "--host", "0.0.0.0", "--port", "8000"]
