FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN apt-get update && apt-get install -y \
    libgl1 \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender-dev \
    libxcb1 \
    && rm -rf /var/lib/apt/lists/*
RUN pip install --no-cache-dir -r requirements.txt

COPY BE /app/BE
COPY ml /app/ml

ENV PYTHONPATH=/app
CMD ["uvicorn", "BE.main:app", "--host", "0.0.0.0", "--port", "8000"]
